#%RAML 1.0
title: chatgpt-eapi
description: ChatGTP API with OpenAI Connector

types:
 Query:
   type: object
   properties:
     message: string
     apikey: string
        
/query:
#  get:
#    description: Returns a list of notifications
#    queryParameters:
#      status:
#        description: Filter by status
#        type: string
#        required: false
#    responses:
#      200:
#        body:
#          application/json:
#            type: Notification[]
#            example:
#              -
#                id: 5f7486a192ea33fe3e2f08b9
#                status: pending
#                message: This is a sample notification
#                priority: High
#                groupId: 1
#              -
#                id: 5f74939b92ea33fe3e2f08c6
#                status: complete
#                message: This is a sample notification
#                priority: Log
#                groupId: 0
 post:
   description: Query to ChatGPT
   body:
     application/json:
       type: Query
       example:
         message: Message to ChatGPT
         apikey: ABCDE

   responses:
     200:
       description: Notification has been created
       body:
         application/json:
           example: {
             "answer": "Message from ChatGPT"
           }